services:
  sunaiforum-bot:
    container_name: sunaiforum-bot
    image: woodchen/sunaiforum-bot:latest
    restart: always
    environment:
      - BOT_TOKEN=719XXX42:AAEydXXXX8rg #换成自己的机器人ID
      - ADMIN_ID=5912366993 #换成自己的ID
      - CHAT_ID=-100xxx781  #换成自己的群ID
      - SYMBOLS=DOGS/USDT,TON/USDT
      - TZ=Asia/Singapore
    volumes:
      - ./data:/app/data